### ISSUE TITLE
A Bug In Macro

### ISSUE THREAD

**Issue by thetaQ** [pthrasher/c-generic-ring-buffer#4]
You should surround your macro by do{...}while(0)

**Comment by Niondir** [comment]
It will work in cases where you do:

```
if (true)
   MACRO
```

Which would fail with multiple statements inside the macro (only the first would be guarded by the if-statement). The do-while wrapper makes the macro safe in any context.

**Comment by pthrasher** [comment]
If someone would like to contribute this with tests, I'll happily pull it in. :-)
