### ISSUE TITLE
Pretty fat bug here: it's not a ring buffer!

### ISSUE THREAD

**Issue by mfp20** [pthrasher/c-generic-ring-buffer#9]
It's a simple linear buffer, it doesn't wrap around!

I love the header-only libs, and simplicity is cool. But the whole project should be renamed. I'd also rename the BUF.start and BUF.end elements in the structure to BUF.WriteIndex and BUF.ReadIndex, or alike.

**Comment by pthrasher** [comment]
Linear buffers require shifting the index of every element. This does not. Of you continue writing, you will overflow into "index 0" again. That's why this is a ring buffer. 

I certainly could be missing some important nuance, and I welcome further explanation... but I don't see any way that this is a not a ring buffer.

**Comment by mfp20** [comment]
> Linear buffers require shifting the index of every element.

The name "linear buffer" can be many different things. Academics have specific names for a gazillion of different memory management structures. Can be FIFO, FILO, LOFI... a stack... a pool... Whatever is "linear" doesn't really need to shift indexes of every element.

> Of you continue writing, you will overflow into "index 0" again. That's why this is a ring buffer.

It overflows, overwriting the content in the memory segment. It doesn't manage the overflow. In a real ring buffer, end and start doesn't matter; there's a writing head and a reading tail. Those 2 indexes get updated taking into considerantion the chances of a wrap around in the middle of the multibytes writing/reading. If you don't take into consideration this wrap around mechanic, it isn't a ring buffer. It's just a linear buffer that restarts once it is full, instead of returning an error in the case the buffer is full.

**Comment by itavero** [comment]
> It's just a linear buffer that restarts once it is full, instead of returning an error in the case the buffer is full.

So you're just upset that you have to call `isBufferEmpty` before reading and `isBufferFull` before writing? 🤷‍♂️

**Comment by mfp20** [comment]
> > It's just a linear buffer that restarts once it is full, instead of returning an error in the case the buffer is full.
> 
> So you're just upset that you have to call `isBufferEmpty` before reading and `isBufferFull` before writing? 🤷‍♂️

Don't have any emotion about that; it's a mechanical issue. The only point of naming things is to identify a specific entity (a person, an object, a ... data structure); if you use "apple" to name a "banana", when someone searches for an apple, he gets a banana. Making the naming habit useless, and the naming space a nightmare. And let's not talk about the whole legal trademark castle built on top of this naming habit...

Outside a university, in the real world, there's no need to be too specific (ie: both a granny smith and a golden delicious are apples); but the banana doesn't fit the apple task.

Anyway, thanks for the code. I adapted it to my needs by modding and adding some macros.

**Comment by itavero** [comment]
Not that it's always the best source of information, but here's a short excerpt from the [Wikipedia page on circular buffers (a.k.a. ring buffers)](https://en.m.wikipedia.org/wiki/Circular_buffer):

> A property of the circular buffer is that when it is full and a subsequent write is performed, then it starts overwriting the oldest data.

**Comment by mfp20** [comment]
> Not that it's always the best source of information, but here's a short excerpt from the [Wikipedia page on circular buffers (a.k.a. ring buffers)](https://en.m.wikipedia.org/wiki/Circular_buffer):
> 
> > A property of the circular buffer is that when it is full and a subsequent write is performed, then it starts overwriting the oldest data.

"Alternatively, the routines that manage the buffer could prevent overwriting the data and return an error or raise an [exception](https://en.m.wikipedia.org/wiki/Exception_handling)." (same link, just 1 row after; extrapolating single sentences from context doesn't make a point)

Once again: overwriting (or not) doesn't mean much. The reason I wrote is another one: it doesn't manage the wrap around. There are no checks wheter the next element's addr is next as well, or previous, to the current element's addr; one check only to restart the counters (and overwrite). It's not a matter of checking wheter the buffer is full or not. If, as another example, you need to use a DMA to copy data from/to the buffer, it will fail. It's not a big issue: I added my own macros in order to know in advance how many elements are left before the wrap around, and limit the DMA copy to this linear region only (ie: in order to copy a whole frame/message spanning across the wrap around, I've to trigger the DMA once again); ie: now the wrap around is externally manageable (and not managed, yet; not by this buffer implementation). I rounded the banana to make it a bit more apple-ly.
That's why often data structures are made by pointers/addresses rather than numeric indexes.

Let me be clear: It is a description issue only; for search sake in github. Functionally speaking instead, it's awesome: minimum cpu cycles, and minimum code, to get the job done; and it leaves space to whatever mods adopters need. Very zen-nish.
Probably by adding some macros to get the indexes, or to search for a value, or to get the next linear region before the wrap around ... would make it more ring-y. By now, it's kind of a stretch to define it "ring buffer". It looks more likely an educational tool.

**Comment by pthrasher** [comment]
@mfp20 Thank you for your insights and for engaging in this discussion thoughtfully. I understand your perspective on ring buffers, but I view their definition as broader, with certain features like error throwing on overwrite being optional. This implementation prioritizes simplicity and efficiency, and while it might not satisfy every trait a ring buffer could contain, it aligns with the core concept. I appreciate your feedback and I'm open to suggestions or clarifications in our documentation to better communicate its functionality. I think a good start is probably to mention that you must check if the buffer is full on your own as @itavero pointed out. :-) Also, I'd be happy to incorporate new features that make this more accessible so long as they don't break the core desire to stay very simple. Please feel free to submit a PR.
